Feature: Asteroids - Easy
  Scenario: Horizontal motion
    Given the first picture at 1 :
    """
    A....
    .....
    .....
    .....
    .....
    """
    And the second picture at 2 :
    """
    .A...
    .....
    .....
    .....
    .....
    """
    When we want to determine the positions of asteroids at 3
    Then we should have the following picture :
    """
    ..A..
    .....
    .....
    .....
    .....
    """
  Scenario: Vertical motion
    Given the first picture at 1 :
    """
    A....
    .....
    .....
    .....
    .....
    """
    And the second picture at 2 :
    """
    .....
    A....
    .....
    .....
    .....
    """
    When we want to determine the positions of asteroids at 3
    Then we should have the following picture :
    """
    .....
    .....
    A....
    .....
    .....
    """
  Scenario: Combined motion
    Given the first picture at 1 :
    """
    A....
    .....
    .....
    .....
    .....
    """
    And the second picture at 2 :
    """
    .....
    .A...
    .....
    .....
    .....
    """
    When we want to determine the positions of asteroids at 3
    Then we should have the following picture :
    """
    .....
    .....
    ..A..
    .....
    .....
    """
  Scenario: Negative motion
    Given the first picture at 1 :
    """
    .....
    .....
    ..A..
    .....
    .....
    """
    And the second picture at 2 :
    """
    .....
    .A...
    .....
    .....
    .....
    """
    When we want to determine the positions of asteroids at 3
    Then we should have the following picture :
    """
    A....
    .....
    .....
    .....
    .....
    """
  Scenario: Greater delta
    Given the first picture at 1 :
    """
    A.....
    ......
    ......
    ......
    ......
    ......
    """
    And the second picture at 5 :
    """
    ....A.
    ......
    ......
    ......
    ......
    ......
    """
    When we want to determine the positions of asteroids at 6
    Then we should have the following picture :
    """
    .....A
    ......
    ......
    ......
    ......
    ......
    """
  Scenario: Multiple asteroids
    Given the first picture at 1 :
    """
    A.....
    ......
    B.....
    ......
    ......
    ......
    """
    And the second picture at 3 :
    """
    .A....
    B.....
    ......
    ......
    ......
    ......
    """
    When we want to determine the positions of asteroids at 5
    Then we should have the following picture :
    """
    B.A...
    ......
    ......
    ......
    ......
    ......
    """
  Scenario: Depth
    Given the first picture at 1 :
    """
    ..H...
    ......
    E...G.
    ......
    ..F...
    ......
    """
    And the second picture at 6 :
    """
    ......
    ..H...
    .E.G..
    ..F...
    ......
    ......
    """
    When we want to determine the positions of asteroids at 11
    Then we should have the following picture :
    """
    ......
    ......
    ..E...
    ......
    ......
    ......
    """
  Scenario: No motion
    Given the first picture at 0 :
    """
    .....
    .A...
    .....
    ...D.
    .....
    """
    And the second picture at 1255 :
    """
    .....
    .A...
    .....
    ...D.
    .....
    """
    When we want to determine the positions of asteroids at 9999
    Then we should have the following picture :
    """
    .....
    .A...
    .....
    ...D.
    .....
    """
  Scenario: Out of bounds
    Given the first picture at 100 :
    """
    A.........
    B.........
    C.........
    D.........
    E.........
    .........F
    .........G
    .........H
    .........I
    .........J
    """
    And the second picture at 200 :
    """
    .A........
    ..B.......
    ...C......
    ....D.....
    .....E....
    ........F.
    .......G..
    ......H...
    .....I....
    ....J.....
    """
    When we want to determine the positions of asteroids at 300
    Then we should have the following picture :
    """
    ..A.......
    ....B.....
    ......C...
    ........D.
    ..........
    .......F..
    .....G....
    ...H......
    .I........
    ..........
    """
  Scenario: Armageddon
    Given the first picture at 25 :
    """
    .................O..
    .....N...........U..
    .............L.R....
    ....................
    ..........Z..V.H....
    ................X...
    .............P......
    .............A......
    .Q.............T....
    ..................F.
    ....................
    ......K............W
    ...............Y....
    ..............S.....
    ...........JE......D
    ...M................
    ......B..G...C....I.
    ....................
    ....................
    ....................
    """
    And the second picture at 75 :
    """
    G...................
    ...............W....
    ...................C
    ...E................
    ..............K.....
    ...........T........
    ............A.......
    .....P...FLI......N.
    ....................
    ........D...........
    ......S..Y.........M
    .........B....Z.....
    ....................
    ....V.............J.
    .........O..........
    ..X...........U.....
    ....................
    ....................
    ..Q................R
    .......H............
    """
    When we want to determine the positions of asteroids at 100
    Then we should have the following picture :
    """
    ..................K.
    ....................
    .......I............
    .........T..........
    ....................
    ...........A........
    ..D.F...............
    .P..................
    ..S.......B.........
    ......Y.L...........
    ....................
    ....................
    ....................
    ....................
    ................Z...
    ....................
    ....................
    ....................
    ....................
    ....................
    """
